import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const modernVerses = {
  "1.1": "Dhritarashtra said: On the field of Kurukshetra, where my sons and the sons of Pandu have gathered ready for battle, what is happening now?",
  "1.2": "Sanjaya said: Seeing the army of the Pandavas arranged for battle, King Duryodhana approached his teacher Drona and spoke.",
  "1.3": "Duryodhana said: Look at this powerful army of the Pandavas, skillfully arranged by your own student, the son of Drupada.",
  "1.4": "Among them are many great warriors and skilled archers, equal in battle to Bhima and Arjuna.",
  "1.5": "There are also many renowned fighters such as Dhrishtaketu, Chekitana, the king of Kashi, Purujit, Kuntibhoja, and Shaibya.",
  "1.6": "There are brave warriors like Yudhamanyu and Uttamaujas, along with the sons of Draupadi and the son of Subhadra, all mighty fighters.",
  "1.7": "But listen also to the leaders of our own army, so that you may understand our strength.",
  "1.8": "There are great warriors here as well: yourself, Bhishma, Karna, Kripa, Ashvatthama, Vikarna, and the son of Somadatta.",
  "1.9": "Many other brave fighters stand with us, prepared to give their lives, skilled in every form of combat.",
  "1.10": "Our army, protected by Bhishma, appears strong, yet the opposing army protected by Bhima seems formidable.",
  "1.11": "Therefore all of you, standing in your positions, must give your full support to protecting Bhishma.",
  "1.12": "Then Bhishma, the great elder of the Kuru dynasty, roared like a lion and blew his conch to encourage Duryodhana.",
  "1.13": "Immediately the battlefield echoed with the sound of conches, drums, horns, and trumpets, creating a thunderous roar.",
  "1.14": "Then Krishna and Arjuna, standing together in their chariot drawn by white horses, blew their conches in response.",
  "1.15": "Krishna blew the conch Panchajanya, Arjuna blew Devadatta, and Bhima blew his powerful conch Paundra.",
  "1.16": "King Yudhishthira blew Anantavijaya, while Nakula and Sahadeva sounded their conches Sughosha and Manipushpaka.",
  "1.17": "Other great warriors such as the king of Kashi, Shikhandi, Dhrishtadyumna, Virata, and Satyaki also sounded their conches.",
  "1.18": "Drupada, the sons of Draupadi, and Abhimanyu all blew their conches, each adding to the rising sound across the battlefield.",
  "1.19": "The powerful sound echoed through the sky and across the earth, striking fear into the hearts of the sons of Dhritarashtra.",
  "1.20": "Seeing the armies prepared for battle, Arjuna lifted his bow and spoke to Krishna.",
  "1.21": "Arjuna said: Place my chariot between the two armies so that I may look at those who stand ready to fight.",
  "1.22": "I want to see who has gathered here and with whom I must fight in this great conflict.",
  "1.23": "Let me see those who have come to support the ambitions of Dhritarashtra’s son.",
  "1.24": "Sanjaya said: Hearing Arjuna’s request, Krishna guided the chariot into the space between the two armies.",
  "1.25": "He placed it before the great warriors and said to Arjuna, 'Look upon those gathered here.'",
  "1.26": "Arjuna then saw among the armies his own relatives, teachers, elders, friends, and loved ones standing on both sides.",
  "1.27": "Seeing his entire family gathered for battle, Arjuna was filled with deep compassion.",
  "1.28": "Overcome with sorrow, he spoke to Krishna.",
  "1.29": "Arjuna said: My limbs feel weak, my mouth is dry, and my body trembles as I look at those standing before me.",
  "1.30": "My bow slips from my hand, my skin burns, and my mind feels unsteady and confused.",
  "1.31": "I see no good in killing my own people in this battle.",
  "1.32": "I do not desire victory, power, or pleasure if the price is the destruction of those I love.",
  "1.33": "Those for whose sake we seek success and happiness now stand here ready to fight against us.",
  "1.34": "Teachers, fathers, sons, grandfathers, uncles, in-laws, and friends are all here on this battlefield.",
  "1.35": "I do not wish to harm them, even if they were to attack me. No kingdom or power could justify such a cost.",
  "1.36": "What joy could come from destroying our own people? Only sorrow and regret would remain.",
  "1.37": "How could we find happiness after killing those who belong to our own family?",
  "1.38": "They may be blinded by ambition and unable to see the harm they are causing.",
  "1.39": "But if we clearly see the consequences, why should we take part in such destruction?",
  "1.40": "When families and communities are destroyed, the values and responsibilities that hold them together begin to disappear.",
  "1.41": "When these values collapse, disorder spreads through society and relationships.",
  "1.42": "This breakdown harms both the present generation and those who come after.",
  "1.43": "When social order collapses, long-standing traditions and responsibilities fade away.",
  "1.44": "We have heard that when family values are destroyed, society falls into lasting suffering.",
  "1.45": "Driven by the desire for power and pleasure, we now stand on the edge of harming our own people.",
  "1.46": "It would be better for me to lay down my weapons and be struck down than to take part in destroying those I love.",
  "2.1": "Seeing Arjuna overcome with sorrow and compassion, his eyes filled with tears and his mind troubled, Krishna prepared to guide him.",
  "2.2": "Krishna said: Where has this confusion come from at such a critical moment, Arjuna? This weakness does not lead to growth, honor, or a higher life.",
  "2.3": "Do not give in to this inner weakness. It does not suit who you truly are. Rise above this faintheartedness and stand up with courage.",
  "2.4": "Arjuna said: How can I raise my weapons against Bhishma and Drona in battle? They are my teachers and worthy of my deepest respect.",
  "2.5": "It would be better to live in this world by begging than to gain power by killing those who guided and taught me. Any success gained through their suffering would feel stained.",
  "2.6": "I cannot even tell what would be better, whether we should defeat them or they defeat us. Those very people whose death would make life meaningless now stand before us in battle.",
  "2.7": "My judgment is clouded and my mind is confused about what is right. I ask you to guide me. I am your student now. Teach me what truly leads to the good.",
  "2.8": "Nothing I can imagine, not even great wealth or power, could remove the sorrow that weighs down my spirit.",
  "2.9": "After saying, \"I will not fight,\" Arjuna fell silent, overwhelmed by his inner conflict.",
  "2.10": "Standing between the two armies, Krishna spoke calmly to Arjuna, who was grieving and confused.",
  "2.11": "Krishna said: You grieve for those who need not be grieved for, yet you speak as though you understand life deeply. The truly wise do not grieve excessively for the living or the dead.",
  "2.12": "There was never a time when I did not exist, nor you, nor these people. And there will never be a time when we cease to exist.",
  "2.13": "Just as the body passes through childhood, youth, and old age, the soul continues beyond the body. One who understands this is not confused by change.",
  "2.14": "Pleasure and pain arise from contact with the world through the senses. They come and go like changing seasons. Learn to endure them with patience, knowing they are temporary.",
  "2.15": "One who remains steady in both pleasure and pain develops deep inner strength. Such a person becomes ready for liberation.",
  "2.16": "What is unreal has no lasting existence, and what is real never ceases to be. Those who perceive truth understand the difference.",
  "2.17": "Know that the soul, which pervades all life, is indestructible. Nothing can destroy this eternal essence.",
  "2.18": "The body is temporary, but the soul that dwells within it is eternal and indestructible. Understanding this helps remove the fear that clouds action.",
  "2.19": "One who believes the soul can kill or be killed does not truly understand. The soul neither destroys nor is destroyed.",
  "2.20": "The soul is never born and never dies. It has always existed and will always exist. It is timeless and cannot be destroyed when the body is destroyed.",
  "2.21": "One who truly understands the soul as eternal and unchanging cannot see themselves as the ultimate cause of life or death.",
  "2.22": "Just as a person discards worn-out clothes and puts on new ones, the soul leaves old bodies and takes on new ones.",
  "2.23": "Weapons cannot cut the soul, fire cannot burn it, water cannot drown it, and wind cannot dry it.",
  "2.24": "The soul is eternal, stable, and beyond physical harm. It is present everywhere and remains unchanged.",
  "2.25": "Because the soul cannot be seen or grasped by the senses, it is often misunderstood. Yet understanding its nature removes unnecessary sorrow.",
  "2.26": "Even if you believed life begins and ends with the body, you would still have no reason to grieve excessively.",
  "2.27": "Death is certain for those who are born, and birth follows death. This cycle is part of existence and cannot be avoided.",
  "2.28": "All beings begin unseen, appear for a time, and then disappear again. Recognizing this makes excessive grief unnecessary.",
  "2.29": "Some see the soul as a profound mystery, others speak of it with wonder, and many hear about it yet still struggle to truly understand it.",
  "2.30": "The soul within every living being is eternal and indestructible. Knowing this removes the need for despair.",
  "2.31": "Consider also your duty. When you clearly understand your responsibility, hesitation fades.",
  "2.32": "Moments that test courage and character sometimes arrive unexpectedly. Meeting them with integrity opens the path to growth.",
  "2.33": "Avoiding your responsibility out of fear or confusion harms both your integrity and your sense of purpose.",
  "2.34": "For someone who values honor and character, losing self-respect can feel worse than losing everything else.",
  "2.35": "Those who once respected your strength may believe you withdrew out of fear.",
  "2.36": "Your critics will speak harshly about your choice. Such judgment can be more painful than the challenge itself.",
  "2.37": "If you face your responsibility and fall, your courage still carries meaning. If you succeed, you gain the world before you. Either way, act with resolve.",
  "2.38": "Approach action with a balanced mind, seeing gain and loss, success and failure with the same clarity. When your inner state is steady, your actions remain pure.",
  "2.39": "So far this wisdom has been explained through understanding. Now learn how to live it through disciplined action, which frees a person from attachment to results.",
  "2.40": "No sincere effort on the path of inner discipline is ever wasted. Even a small step in this direction protects the mind from great fear.",
  "2.41": "A mind guided by wisdom becomes steady and focused. A restless mind, pulled by countless desires, moves endlessly in many directions.",
  "2.42": "Some people become absorbed in the elaborate promises found in the Vedas (ancient teachings) and believe there is nothing higher.",
  "2.43": "Driven by desire for pleasure, power, and status, they focus on rituals and rewards rather than deeper understanding.",
  "2.44": "When the mind becomes absorbed in pleasure, status, and power, it loses the stillness required for true understanding.",
  "2.45": "The Vedas (ancient teachings) often describe life through the forces of nature that shape human behavior. Rise beyond these forces. Remain steady, free from constant craving and the anxiety of gaining and keeping possessions.",
  "2.46": "For one who understands the deeper reality of life, the many teachings serve a role similar to a small well when water is abundant everywhere.",
  "2.47": "You are responsible for your actions, but never for the outcomes they produce. Give your full attention to the work itself, without clinging to the results.",
  "2.48": "Perform your actions with inner balance. Remain steady in success and failure. This steadiness of mind is true inner discipline.",
  "2.49": "Actions driven only by the desire for reward keep the mind bound to outcomes. Let wisdom guide your actions instead.",
  "2.50": "When action is guided by clear understanding rather than craving, the mind rises above both success and failure. This is the art of skillful and balanced action.",
  "2.51": "Those who act with wisdom and let go of attachment to results move beyond cycles of anxiety and dissatisfaction and move toward liberation.",
  "2.52": "When your understanding moves beyond confusion, you become less disturbed by the countless opinions and doctrines that surround you.",
  "2.53": "When the mind stops wavering among competing ideas and becomes steady in deep reflection, true clarity arises.",
  "2.54": "Arjuna said: What does a person of steady wisdom look like? How do they speak, live, and move through the world?",
  "2.55": "Krishna said: One whose mind has let go of restless desires and finds quiet contentment within the soul is said to possess steady wisdom.",
  "2.56": "Such a person is not shaken by sorrow, does not chase pleasure, and remains free from attachment, fear, and anger.",
  "2.57": "One who moves through life without clinging to what is pleasant or rejecting what is unpleasant keeps their understanding firmly grounded.",
  "2.58": "Just as a turtle withdraws its limbs for protection, a wise person can draw the senses inward when needed and remain centered within.",
  "2.59": "Resisting desire may quiet the senses for a time, yet the craving can remain. When deeper understanding awakens, even the craving fades.",
  "2.60": "The senses are powerful and restless. Even a thoughtful person can be carried away by them if the mind is not watchful.",
  "2.61": "When the senses are guided by awareness and discipline, the mind becomes steady and wisdom takes root.",
  "2.62": "When the mind dwells repeatedly on something, attachment begins to grow. From attachment arises desire, and when desire is blocked, anger follows.",
  "2.63": "Anger clouds perception. From this confusion comes loss of judgment, and when judgment collapses, one’s path is easily lost.",
  "2.64": "One who moves through the world with disciplined senses, free from attraction and aversion, gradually discovers inner serenity.",
  "2.65": "From serenity comes the quieting of inner turmoil. In that calmness, the mind becomes clear and steady.",
  "2.66": "A restless mind cannot know wisdom. Without wisdom there is no peace, and without peace there can be no lasting happiness.",
  "2.67": "When the mind follows wandering senses, it sweeps away understanding just as strong winds carry a boat off course.",
  "2.68": "When the senses are guided and restrained, wisdom becomes firmly established.",
  "2.69": "What appears like night to most people is clear awareness to the wise. What others chase in waking life appears empty to one who sees clearly.",
  "2.70": "A peaceful person remains steady even as many desires arise, just as the ocean remains full and unmoved by the rivers that flow into it.",
  "2.71": "Peace belongs to the one who lets go of craving, possessiveness, and the constant claim of the ego.",
  "2.72": "This is the state of deep spiritual clarity. One who becomes firmly established in it is no longer confused and moves toward liberation.",
  "3.1": "Arjuna said: If understanding and wisdom are greater than action, why do you urge me toward such a difficult action?",
  "3.2": "Your words seem to point in different directions and leave me confused. Please tell me clearly the one path that truly leads to the highest good.",
  "3.3": "Krishna said: There are two natural paths in life. One is the path of deep understanding and contemplation. The other is the path of disciplined action in the world.",
  "3.4": "A person does not reach freedom by avoiding action. Nor does simply giving things up lead to true fulfillment.",
  "3.5": "No one can remain without action even for a moment. The forces of nature within us constantly move us to act.",
  "3.6": "One who outwardly restrains action but continues to dwell on desires in the mind lives in self-deception.",
  "3.7": "But one who brings the senses under the guidance of the mind and acts with discipline, without attachment, walks a higher path.",
  "3.8": "Perform the responsibilities that belong to you. Action is better than inaction, for even sustaining life requires action.",
  "3.9": "Actions performed only for personal gain bind the mind. But actions offered in a spirit of service and contribution bring freedom.",
  "3.10": "At the beginning of creation, humanity was given the principle of selfless offering and cooperation. Through this, life would grow and flourish.",
  "3.11": "When people support the natural order of life, that same order supports them in return. Through this mutual care, life moves toward harmony.",
  "3.12": "Those who receive the gifts of life without contributing back break the natural balance of giving and receiving.",
  "3.13": "Those who live with gratitude and share what they receive are freed from the burden of selfish living. Those who live only for themselves deepen their own suffering.",
  "3.14": "Life depends on nourishment, nourishment depends on nature, and nature flourishes when human action is aligned with balance and responsibility.",
  "3.15": "Right action arises from wisdom preserved in the Vedas (ancient teachings), and those teachings arise from the deeper order of reality. In this way, the sacred order of life is sustained through action.",
  "3.16": "One who refuses to participate in this cycle of responsibility and contribution, choosing only pleasure and self-interest, lives without purpose.",
  "3.17": "But one who finds fulfillment within the soul, who is inwardly content and complete, no longer depends on external duties for inner satisfaction.",
  "3.18": "Such a person gains nothing by acting and loses nothing by not acting, for their peace no longer depends on external outcomes.",
  "3.19": "Therefore perform your responsibilities without attachment. Through action carried out with this spirit, one moves toward liberation.",
  "3.20": "Great leaders of the past reached fulfillment through action. By acting with responsibility, they preserved the balance of the world.",
  "3.21": "Whatever a respected person does, others naturally follow. The example they set becomes the path many people take.",
  "3.22": "Even though there is nothing I personally need to achieve, I continue to act.",
  "3.23": "If I stopped acting, people everywhere would follow that example.",
  "3.24": "If those with influence abandoned their responsibilities, confusion would spread and society itself would fall into disorder.",
  "3.25": "Just as those without understanding act with attachment, the wise should act without attachment, always seeking the welfare of the world.",
  "3.26": "The wise should not create confusion for those who are still attached to action. Instead, they should guide by example and perform actions with discipline.",
  "3.27": "All actions are carried out by the forces of nature. But the ego convinces a person to believe, 'I alone am the doer.'",
  "3.28": "One who understands the truth sees that actions arise from the interaction of nature's forces and therefore does not become trapped in attachment.",
  "3.29": "Those whose understanding is limited become attached to their actions. The wise should guide them gently rather than disturb their progress.",
  "3.30": "Offer your actions to the highest truth, center your mind in the soul, and act without desire or possessiveness. Perform your duty without inner conflict.",
  "3.31": "Those who follow this teaching with sincerity and trust gradually free themselves from the burden of selfish action.",
  "3.32": "But those who reject this wisdom and refuse to follow it remain confused and lose their clarity of judgment.",
  "3.33": "Even wise people act according to their nature. All beings follow their nature. Simply forcing restraint cannot fully change this.",
  "3.34": "Each sense has its natural attractions and dislikes. One should not become controlled by them, for they can block the path of clarity.",
  "3.35": "It is better to live according to your own path, even imperfectly, than to imitate the path of another perfectly. Living someone else's path brings inner conflict.",
  "3.36": "Arjuna said: What drives a person to act wrongly, even against their own better judgment, as if pushed by some force?",
  "3.37": "Krishna said: It is desire, which later turns into anger. Born from restless passion, it consumes the mind and becomes a powerful inner enemy.",
  "3.38": "Just as fire can be hidden by smoke or a mirror by dust, the clarity of the mind can be covered by this force.",
  "3.39": "This restless desire clouds wisdom and keeps a person from seeing clearly. Like fire, it is never satisfied.",
  "3.40": "Desire lives in the senses, the mind, and the intellect. Through these it distorts understanding and confuses the soul.",
  "3.41": "Therefore begin by bringing the senses under discipline. In doing so, you weaken this force that destroys wisdom and inner clarity.",
  "3.42": "The senses are powerful, but the mind is greater than the senses. The intellect is greater than the mind. Beyond even the intellect lies the soul.",
  "3.43": "Knowing that the soul is higher than the intellect, steady the mind through inner awareness and overcome this powerful enemy called desire.",
  "4.1": "Krishna said: I first taught this timeless path of inner discipline to Vivasvan. Vivasvan passed it to Manu, and Manu passed it to Ikshvaku.",
  "4.2": "In this way the teaching was preserved through a lineage of wise leaders. But over time the understanding of this path faded from the world.",
  "4.3": "That same ancient wisdom I now share with you, because you are both my friend and a sincere seeker. This teaching is a profound truth.",
  "4.4": "Arjuna said: You were born in recent times, while Vivasvan lived long ago. How should I understand that you taught this in the beginning?",
  "4.5": "Krishna said: Many lifetimes have passed for both of us. I remember them all, but you do not.",
  "4.6": "Though I am unborn and my nature is eternal, I appear in the world through my own power, guiding the course of life.",
  "4.7": "Whenever balance and righteousness decline and disorder begins to rise, I manifest in the world.",
  "4.8": "I appear to protect those who live with integrity, to restrain harmful forces, and to restore balance in the world. This happens again and again through time.",
  "4.9": "One who truly understands the deeper nature of these actions and manifestations is no longer bound by the cycle of rebirth and moves toward liberation.",
  "4.10": "Many people, freed from attachment, fear, and anger, have purified themselves through understanding and have come to share in this higher awareness.",
  "4.11": "People approach truth in many different ways. Whatever path they sincerely follow, it ultimately leads toward the same reality.",
  "4.12": "Those who seek quick success often turn toward limited goals and temporary rewards, which can be gained quickly through effort in the world.",
  "4.13": "Human society developed different roles based on natural qualities and types of work. Though I established this order, I remain beyond all action.",
  "4.14": "Actions do not bind one who acts without personal desire for results. Understanding this allows a person to remain free even while acting.",
  "4.15": "Knowing this truth, seekers of liberation in ancient times still performed their responsibilities. Therefore act as they did, with clarity and discipline.",
  "4.16": "Even thoughtful people struggle to understand what true action is and what inaction means. I will explain this so that you may act wisely.",
  "4.17": "One must understand the difference between right action, harmful action, and the deeper meaning of inaction. The nature of action is subtle and complex.",
  "4.18": "One who can see stillness within action and meaningful action within stillness possesses true understanding.",
  "4.19": "When a person's actions are free from selfish desire and driven by clear understanding, the wise recognize that person as truly awakened.",
  "4.20": "One who releases attachment to results, who is content and inwardly independent, remains inwardly free even while acting.",
  "4.21": "When a person acts with self-control, without possessiveness or expectation, their actions no longer create inner burden.",
  "4.22": "Content with whatever comes, steady in both success and failure, and free from envy, such a person remains unbound by their actions.",
  "4.23": "When someone acts without attachment, with the mind grounded in understanding, their actions dissolve naturally and leave no lasting burden.",
  "4.24": "For one who sees clearly, every aspect of action becomes part of the same deeper reality. The offering, the act, and the purpose all arise from the same ultimate reality.",
  "4.25": "Some seek truth through devotion and reverence, while others offer their actions themselves into the fire of deeper understanding.",
  "4.26": "Some practice discipline by restraining the senses, while others transform sensory experiences through awareness and self-control.",
  "4.27": "Others dedicate all activities of the senses and the life force into the discipline of self-mastery guided by knowledge.",
  "4.28": "Some practice generosity, some practice discipline and restraint, and others dedicate themselves to study and the pursuit of knowledge.",
  "4.29": "Some practice deep control of breath and life energy, using it as a path toward inner balance and awareness.",
  "4.30": "Others regulate their habits and lifestyle carefully, dedicating all aspects of life to a path of awareness and self-discipline.",
  "4.31": "Those who live in the spirit of offering and contribution move toward the eternal reality. A life without such contribution leads nowhere meaningful.",
  "4.32": "Many different forms of dedicated action exist. Understanding that they all arise from purposeful action helps a person move toward liberation.",
  "4.33": "Yet the offering of knowledge is greater than material offerings, because all meaningful action ultimately finds its fulfillment in understanding.",
  "4.34": "Approach those who have realized truth with humility, sincere questions, and a willingness to learn. Those who see clearly can guide you toward understanding.",
  "4.35": "When you gain this understanding, confusion will no longer return. You will see all beings connected within the soul and within the deeper reality.",
  "4.36": "Even if someone has lived with many mistakes, the clarity of knowledge can carry them across those errors like a raft across a river.",
  "4.37": "Just as fire reduces wood to ashes, the fire of knowledge burns away the burden of past actions.",
  "4.38": "Nothing purifies the mind more deeply than true knowledge. With time and sincere effort, a person discovers this wisdom within the soul.",
  "4.39": "One who has trust, dedication, and disciplined senses gains knowledge. With that knowledge comes deep and lasting peace.",
  "4.40": "But the person who lacks understanding, trust, and clarity remains trapped in doubt. Such doubt destroys both peace and happiness.",
  "4.41": "One who acts with inner discipline and whose doubts are removed through knowledge remains free, even while performing actions.",
  "4.42": "Therefore cut away the doubts that arise from ignorance through the clarity of knowledge. Stand in inner discipline and move forward with courage.",
  "5.1": "Arjuna said: You praise both renouncing action and acting with discipline. Tell me clearly which of these paths is truly better.",
  "5.2": "Krishna said: Both renouncing selfish motives and acting with inner discipline can lead to the highest good. But acting with discipline while fulfilling one’s responsibilities is the better path.",
  "5.3": "A true renunciant is not one who abandons work, but one who lets go of hatred and craving. Free from these inner conflicts, such a person moves easily toward liberation.",
  "5.4": "Only the unwise see understanding and disciplined action as separate paths. One who is established in either path gains the benefits of both.",
  "5.5": "The fulfillment reached through deep understanding is also reached through disciplined action. One who sees these paths as one truly understands.",
  "5.6": "Renouncing action without inner discipline is difficult. But one who acts with awareness and balance quickly moves toward ultimate reality.",
  "5.7": "One who acts with inner discipline, whose mind is pure and senses are under control, sees the same soul in all beings. Even while acting, such a person remains untouched by the burden of action.",
  "5.8": "One who understands truth knows inwardly, 'I am not the doer.' Even while seeing, hearing, touching, eating, moving, resting, and breathing, they remain aware that life is simply unfolding through them.",
  "5.9": "Speaking, letting go, grasping, or opening and closing the eyes, such a person understands that the senses are simply interacting with the world.",
  "5.10": "One who performs actions while offering them to the highest reality and letting go of attachment remains untouched by wrongdoing, just as a lotus leaf remains untouched by water.",
  "5.11": "Those who practice disciplined action work through body, mind, intellect, and senses without attachment, using action as a way to purify the inner self.",
  "5.12": "When a person releases attachment to the results of action, lasting peace arises. But when actions are driven by desire for results, the mind becomes bound.",
  "5.13": "One who has mastered the mind rests peacefully within the body, understanding that the soul itself neither acts nor causes action.",
  "5.14": "The deeper reality does not create a person’s actions or their sense of agency. These arise from the natural forces of life itself.",
  "5.15": "Ultimate reality does not take on anyone’s wrongdoing or vertex. Ignorance hides true understanding, and because of this people become confused.",
  "5.16": "But when ignorance is removed through knowledge of the soul, that knowledge shines like the sun and reveals the deeper truth of existence.",
  "5.17": "Those whose understanding, awareness, and purpose are rooted in the highest truth move beyond confusion and toward liberation.",
  "5.18": "The wise see with equal vision a humble scholar, a cow, an elephant, a dog, and even one considered an outcast. Their vision sees the same soul in all.",
  "5.19": "Those whose minds rest in equality overcome the illusions of division in this very life. Seeing all with equal vision, they live in harmony with ultimate reality.",
  "5.20": "One who does not become overly excited by pleasant experiences or distressed by unpleasant ones, whose understanding remains steady, lives established in deeper truth.",
  "5.21": "One who no longer depends on external pleasures discovers a deeper joy within the soul. Through inner discipline, such a person experiences lasting happiness.",
  "5.22": "Pleasures that arise from sensory contact inevitably lead to dissatisfaction, because they begin and end. The wise do not place their hopes in them.",
  "5.23": "One who can endure the impulses of desire and anger before leaving the body lives with discipline and finds true happiness.",
  "5.24": "One whose joy, peace, and inner light arise from within the soul reaches ultimate reality and lives in deep harmony with it.",
  "5.25": "Those whose doubts are removed, whose minds are disciplined, and who work for the welfare of all beings move toward liberation.",
  "5.26": "For those who are free from desire and anger and who understand the soul, liberation is close at hand.",
  "5.27": "By withdrawing attention from external distractions, steadying the gaze, and calming the breath, one begins to quiet the restless movements of the mind.",
  "5.28": "A person who has mastered the senses, mind, and intellect, who is free from desire, fear, and anger, lives in a state of inner freedom.",
  "5.29": "Knowing the deeper reality as the source of all effort, the guiding presence of the world, and the friend of all beings, a person attains true peace.",
  "6.1": "Krishna said: One who performs their responsibilities without clinging to the results is the true renunciant and practitioner of inner discipline, not one who simply withdraws from action.",
  "6.2": "What is called renunciation is truly this inner discipline. No one becomes established in it without letting go of self-centered intentions.",
  "6.3": "For one who seeks inner discipline, responsible action is the path. For one who has already found steadiness, inner calm becomes the path.",
  "6.4": "When a person is no longer attached to sensory pleasures or driven by personal motives, they are said to be established in inner discipline.",
  "6.5": "Lift yourself through the strength of your own mind. Do not allow yourself to fall through carelessness. The mind can become either your greatest ally or your greatest obstacle.",
  "6.6": "For one who has mastered the mind, it becomes a trusted friend. But for one who has not, the mind behaves like an enemy.",
  "6.7": "A person who has gained mastery over the mind remains steady in heat and cold, pleasure and pain, honor and dishonor, resting in deep inner calm.",
  "6.8": "One who is satisfied through knowledge and inner realization, whose senses are under control, and who sees a lump of earth, a stone, and gold with equal value has achieved inner balance.",
  "6.9": "One who maintains equal regard toward friend and enemy, toward strangers and relatives, toward the virtuous and the flawed, lives with a higher understanding.",
  "6.10": "A seeker of inner discipline should spend time in quiet reflection, living simply, with mind and body under control, free from constant desire and possessiveness.",
  "6.11": "Choose a clean and peaceful place, and prepare a steady seat that is neither too high nor too low.",
  "6.12": "Sitting there, focus the mind inward and bring the senses under calm awareness. In this way the practice of meditation begins to purify the inner self.",
  "6.13": "Hold the body, head, and neck upright and steady. Let the gaze rest gently without wandering.",
  "6.14": "With a calm mind, free from fear, and with disciplined living, focus the mind on the highest truth and remain steady in meditation.",
  "6.15": "Through steady practice and a disciplined mind, one discovers deep peace and the freedom that arises from union with ultimate reality.",
  "6.16": "This path cannot be followed by one who lives in extremes, eating too much or too little, sleeping too much or too little.",
  "6.17": "But for one who lives with balance in food, recreation, work, and rest, inner discipline becomes a powerful path that removes suffering.",
  "6.18": "When the disciplined mind rests steadily in the soul, free from the pull of desires, a person is said to be established in inner discipline.",
  "6.19": "Just as a lamp in a windless place burns without flickering, so the mind of one who practices meditation remains steady and calm.",
  "6.20": "In meditation the mind becomes still, and the seeker discovers the soul through direct awareness, finding deep contentment within.",
  "6.21": "In that state arises a profound joy that goes beyond the senses and is understood through inner awareness.",
  "6.22": "Once this inner fulfillment is discovered, nothing else appears greater. Even great difficulties cannot shake one who is established in it.",
  "6.23": "This state of freedom from inner suffering is the true meaning of inner discipline. It should be practiced with determination and a steady heart.",
  "6.24": "Let go of all desires born from restless thought, and bring the senses under the guidance of a calm and attentive mind.",
  "6.25": "Little by little, through steady understanding, allow the mind to settle into quietness. Once the mind rests in the soul, let it remain there.",
  "6.26": "Whenever the restless mind wanders, gently bring it back again under the guidance of awareness.",
  "6.27": "Great happiness arises for one whose mind becomes peaceful, whose restless energy is calmed, and whose inner nature is purified.",
  "6.28": "Through continued practice, the seeker becomes free from inner impurities and experiences the limitless joy of union with ultimate reality.",
  "6.29": "One who is established in inner discipline sees the soul present in all beings and all beings within the soul. Such a person sees unity everywhere.",
  "6.30": "One who sees the deeper reality present everywhere and everything within that reality never feels separated from it.",
  "6.31": "One who recognizes the same sacred presence in all beings lives in unity with that presence, even while acting in the world.",
  "6.32": "The highest practitioner is one who sees others as oneself, understanding both their joy and their suffering with equal compassion.",
  "6.33": "Arjuna said: This state of inner balance that you describe seems difficult to maintain, because the mind is so restless.",
  "6.34": "The mind is unstable, powerful, and difficult to control. It seems as hard to master as the wind.",
  "6.35": "Krishna said: The mind is indeed restless and difficult to control. But through steady practice and detachment, it can be guided.",
  "6.36": "Inner discipline is difficult for one who has not learned self-mastery. But for one who practices sincerely and steadily, it can be reached.",
  "6.37": "Arjuna said: What happens to someone who begins this path with sincerity but loses steadiness before reaching completion?",
  "6.38": "Does such a person lose both worldly success and spiritual progress, like a cloud that breaks apart in the sky?",
  "6.39": "Please remove this doubt for me completely, for only you can explain this clearly.",
  "6.40": "Krishna said: No sincere effort toward goodness is ever lost. One who walks this path never truly falls into ruin.",
  "6.41": "Such a person may first experience the rewards of their past goodness and later be born again in a supportive and prosperous environment.",
  "6.42": "Or they may be born into a family of wise seekers, a rare and fortunate beginning in life.",
  "6.43": "In such circumstances they regain the wisdom they developed before and continue their journey toward fulfillment.",
  "6.44": "The influence of past practice naturally guides them forward again. Even the search for inner discipline lifts a person beyond mechanical ritual.",
  "6.45": "With sincere effort across time, the seeker becomes purified and eventually reaches the highest goal of life.",
  "6.46": "One who lives with inner discipline stands higher than one who practices severe austerity, higher than one who only studies, and higher than one who acts without awareness.",
  "6.47": "Among all who practice inner discipline, the one who lives with deep trust, whose heart rests in the highest truth, and who remains inwardly connected to it is the most deeply united.",
  "7.1": "Krishna said: Fix your mind on the highest truth and practice inner discipline with sincerity. In this way you will come to know reality fully and without doubt.",
  "7.2": "I will explain both knowledge and direct understanding. Once this is known, nothing else remains essential to know.",
  "7.3": "Among thousands of people, only a few strive for deeper understanding. And among those who strive, only a rare person truly understands ultimate reality.",
  "7.4": "The physical world is composed of earth, water, fire, air, space, mind, intellect, and ego. These form the basic elements of material existence.",
  "7.5": "But beyond this visible nature is a higher principle, the living consciousness that sustains all life.",
  "7.6": "From these two aspects arise all living beings. The source and dissolution of the entire universe rests in the deeper reality behind them.",
  "7.7": "There is nothing higher than that ultimate reality. Just as pearls are held together by a thread, all existence is held together by it.",
  "7.8": "The essence of life appears in many forms: the taste in water, the light of the sun and moon, the sacred sound Om in the Vedas (ancient teachings), the vibration of sound in space, and the strength within human beings.",
  "7.9": "It is the fragrance of the earth, the brilliance of fire, the life within all living beings, and the discipline of those who live with self-restraint.",
  "7.10": "It is the original seed of all existence, the intelligence of the intelligent, and the radiance of what shines brightly in the world.",
  "7.11": "It is the strength of the strong when free from selfish desire, and the natural impulse of life that remains aligned with harmony and responsibility.",
  "7.12": "All states of nature arise from this deeper reality. Though they emerge from it, it remains beyond them.",
  "7.13": "Because people become absorbed in these changing states of nature, they fail to recognize the eternal reality beyond them.",
  "7.14": "The forces of illusion that shape the world are difficult to overcome. But those who seek refuge in the highest truth move beyond this illusion.",
  "7.15": "Those whose understanding is clouded by selfishness and confusion turn away from deeper truth and remain caught in ignorance.",
  "7.16": "Four kinds of people turn toward the highest truth: those seeking relief from suffering, those searching for understanding, those seeking success, and those who already possess wisdom.",
  "7.17": "Among them, the one who truly understands and remains devoted to the highest truth stands above the rest, living in unity with it.",
  "7.18": "All sincere seekers are noble, but the one who recognizes the deeper reality as the ultimate goal becomes fully united with it.",
  "7.19": "After many lifetimes of seeking, the wise person realizes that the entire universe is permeated by the same divine reality. Such a realization is very rare.",
  "7.20": "Those whose understanding is guided by personal desires turn toward many different forms of worship, each shaped by their own nature.",
  "7.21": "Whatever form a person chooses to worship with faith, that faith becomes strengthened through their devotion.",
  "7.22": "Through that devotion they obtain what they seek, though ultimately all such outcomes arise from the same deeper reality.",
  "7.23": "But the results gained through limited understanding are temporary. Those who seek temporary goals reach temporary outcomes, while those who seek the highest truth reach lasting union with it.",
  "7.24": "Those who lack deeper understanding think the ultimate reality appears only in visible form, not realizing its timeless and imperishable nature.",
  "7.25": "Because reality is veiled by the power of illusion, most people do not recognize its eternal nature.",
  "7.26": "The deeper reality knows all beings of the past, present, and future, though few truly know it.",
  "7.27": "From birth, people become caught in confusion through attraction and aversion, losing sight of deeper truth.",
  "7.28": "But those whose lives become purified through good actions rise above this confusion and seek the highest truth with determination.",
  "7.29": "Those who seek freedom from aging and death by turning toward the highest truth come to understand ultimate reality, the soul, and the nature of action.",
  "7.30": "Those who understand the deeper reality behind existence, the forces of nature, and the spirit of sacred offering remain aware of that truth even at the final moment of life",
  "8.1": "Arjuna said: What is Brahman, the ultimate reality? What is the soul? What is the nature of action? And what is meant by the principles that govern existence and the cosmos?",
  "8.2": "How is the sacred presence within the body to be understood, and how can a disciplined person recognize the highest truth at the moment of death?",
  "8.3": "Krishna said: The imperishable ultimate reality is called Brahman. The soul is the deeper self within each being. Action is the creative force that brings life into existence.",
  "8.4": "The changing world represents the field of living beings, while the cosmic intelligence sustains the divine order. Within every living body, the deeper presence guiding all sacrifice and transformation is the same ultimate reality.",
  "8.5": "Whoever remembers the highest truth at the moment of death reaches that state without doubt.",
  "8.6": "Whatever a person holds in their mind at the final moment of life reflects the state they have cultivated throughout their life.",
  "8.7": "Therefore remember the highest truth at all times while continuing to perform your responsibilities. With mind and understanding centered in that truth, you will reach it.",
  "8.8": "With a disciplined mind that does not wander, one who continually reflects on the highest reality eventually realizes it.",
  "8.9": "That supreme reality is the eternal witness, the ancient source of all, the subtle sustainer of existence, radiant beyond darkness and beyond ordinary understanding.",
  "8.10": "At the final moment, one whose mind remains steady in devotion and discipline, focusing inward with full awareness, reaches that supreme reality.",
  "8.11": "The state described in the Vedas (ancient teachings) as imperishable is sought by those who live with discipline and self-restraint. I will explain this state briefly.",
  "8.12": "By withdrawing attention from external distractions, steadying the mind within the heart, and directing the life energy upward, one enters deep concentration.",
  "8.13": "Uttering the sacred sound Om while remembering the highest truth at the moment of departure leads the seeker toward the supreme goal.",
  "8.14": "For the one who remembers the highest truth constantly and without distraction, realization becomes easy to attain.",
  "8.15": "Those who reach this realization do not return again to the cycle of suffering in this temporary world.",
  "8.16": "Even the highest realms of existence are temporary. But reaching the ultimate reality brings freedom from rebirth.",
  "8.17": "Those who understand the vast cycles of cosmic time understand the rhythm of creation and dissolution.",
  "8.18": "From the unseen source all visible beings arise, and into that same unseen reality they dissolve again.",
  "8.19": "This cycle repeats endlessly as life appears and disappears again and again.",
  "8.20": "Beyond this cycle of appearance and disappearance lies an eternal reality that never fades.",
  "8.21": "That eternal and imperishable state is the supreme goal. Once it is reached, one does not return to the cycle of rebirth.",
  "8.22": "This supreme reality can be realized through wholehearted devotion. It pervades all beings and holds the entire universe within it.",
  "8.23": "Now I will explain the paths by which seekers depart this life either to return again or to move beyond the cycle of return.",
  "8.24": "Those who depart during the path symbolized by light move toward realization and do not return.",
  "8.25": "Those who depart along the path symbolized by darkness eventually return again to the cycle of life.",
  "8.26": "These two paths have long been understood as the paths of return and non-return.",
  "8.27": "One who understands these truths is not confused by them. Therefore remain steady in inner discipline at all times.",
  "8.28": "Understanding this path goes beyond the rewards promised in the Vedas (ancient teachings), rituals, austerities, or charity, leading instead to the highest and eternal reality.",
  "9.1": "Krishna said: Because you listen with an open mind, I will share with you a deeply hidden wisdom together with the understanding that brings it to life. Knowing this frees a person from confusion and harmful action.",
  "9.2": "This is the highest knowledge and the deepest insight. It purifies the mind, can be directly experienced, is natural to live by, and never fades.",
  "9.3": "Those who lack trust in this path fail to recognize the deeper reality and remain caught in the cycle of ordinary life.",
  "9.4": "The entire universe is pervaded by an unseen presence. All beings exist within it, though it is not confined by them.",
  "9.5": "Yet in another sense, beings do not contain that presence. Such is the mystery of existence: it supports all life without being limited by it.",
  "9.6": "Just as the wind moves everywhere while resting within space, all beings exist within the vast field of existence.",
  "9.7": "At the end of a cosmic cycle, all beings return to their source. When a new cycle begins, they arise again.",
  "9.8": "Through the forces of nature, life unfolds again and again, expressing the rhythms of creation.",
  "9.9": "Yet these processes do not bind the source of existence, which remains unattached and unaffected.",
  "9.10": "Under the guidance of this deeper order, nature gives rise to all forms of life and the world continues to evolve.",
  "9.11": "Some fail to recognize this deeper presence when it appears through human form, not seeing the greater reality behind it.",
  "9.12": "Driven by confusion and selfish desire, they pursue empty hopes and actions that lead nowhere meaningful.",
  "9.13": "But those of deeper understanding recognize the source of all beings and devote themselves to it wholeheartedly.",
  "9.14": "With steady determination they seek truth, living with devotion, humility, and discipline.",
  "9.15": "Some approach this truth through devotion, others through knowledge, and others by recognizing its presence in many forms throughout the universe.",
  "9.16": "Every sacred act, offering, and transformation ultimately arises from the same source of existence.",
  "9.17": "That source is the origin of the world, its nurturer and sustainer, the wisdom behind the Vedas (ancient teachings), and the sacred sound Om.",
  "9.18": "It is the goal of life, the support of existence, the witness within all beings, the refuge and the friend, the origin and the end of all things.",
  "9.19": "It appears through the forces of nature, through life and death, through presence and absence.",
  "9.20": "Those who perform rituals seeking heavenly rewards may reach those states for a time and enjoy their results.",
  "9.21": "But when the results of their actions are exhausted, they return again to the ordinary cycle of life.",
  "9.22": "Those who devote themselves to the highest reality with steady awareness find that what they truly need is provided and what they have is preserved.",
  "9.23": "Even those who worship other forms with sincere faith are ultimately directing their devotion toward the same deeper source, though they may not yet understand it fully.",
  "9.24": "For the source of existence is the true receiver and sustainer of all acts of devotion, though many do not yet recognize this.",
  "9.25": "Those who seek limited goals reach limited destinations, but those who seek the highest truth move toward union with it.",
  "9.26": "Even a simple offering made with sincerity and devotion is accepted when it comes from a pure heart.",
  "9.27": "Whatever you do, whatever you consume, whatever you offer or give, and whatever discipline you practice, perform it as an offering to the highest truth.",
  "9.28": "Living in this spirit frees you from the burdens created by actions and their consequences.",
  "9.29": "The deeper presence within existence is equal toward all beings. Yet those who turn toward it with devotion experience its presence more fully.",
  "9.30": "Even someone who has lived wrongly can transform if they sincerely turn toward truth with wholehearted dedication.",
  "9.31": "Such a person soon grows into integrity and finds lasting peace. One who sincerely seeks truth is never lost.",
  "9.32": "Anyone who sincerely turns toward the highest truth, regardless of background or circumstance, can reach the highest goal.",
  "9.33": "Recognizing the temporary nature of this world, turn your mind toward the deeper reality that endures.",
  "9.34": "Let your thoughts, devotion, and actions be centered on the highest truth. Living in this awareness leads you toward it.",
  "10.1": "Krishna said: Listen again to this deeper wisdom that I share for your well-being.",
  "10.2": "Even the highest beings do not fully know the origin of the source of existence, because it is the origin of all that exists.",
  "10.3": "One who understands the source of existence as timeless and without beginning becomes free from confusion and inner burden.",
  "10.4": "Qualities such as intelligence, clarity, patience, truthfulness, self-control, peace, joy, and sorrow all arise within the unfolding of existence.",
  "10.5": "Likewise non-violence, balance, contentment, discipline, generosity, reputation, and adversity all emerge within this same field of life.",
  "10.6": "The earliest sages and guiding figures of humanity arose from this deeper source, and through them life continued to develop.",
  "10.7": "One who truly understands this unfolding of existence becomes firmly established in inner discipline.",
  "10.8": "I am the source of all existence. From this source everything arises. Knowing this, the wise live with reverence and devotion.",
  "10.9": "Their minds remain centered on this truth, and they share insight with one another, finding joy in understanding.",
  "10.10": "To those who remain devoted with sincerity, deeper understanding naturally unfolds, guiding them closer to truth.",
  "10.11": "Out of compassion, clarity arises within them and dissolves the darkness of confusion.",
  "10.12": "Arjuna said: You are the supreme reality, the eternal presence, the pure and timeless source that pervades existence.",
  "10.13": "Many wise teachers have spoken of this truth, and now you have revealed it to me directly.",
  "10.14": "I accept your words as true, for the deeper reality is difficult even for divine beings to fully comprehend.",
  "10.15": "Only the source of existence fully knows itself as the origin and ruler of the universe.",
  "10.16": "Please describe the ways this presence expresses itself throughout the world.",
  "10.17": "How may I recognize this deeper presence through constant awareness?",
  "10.18": "Explain again the many ways this presence appears in existence, for hearing this wisdom brings great joy.",
  "10.19": "Krishna said: I will describe some of these expressions, though their full extent cannot be fully spoken.",
  "10.20": "I am the soul present in the heart of every being. I am the beginning, the middle, and the end of all existence.",
  "10.21": "Among shining lights I am the sun, among stars the moon, and among sustaining forces those that bring order to the cosmos.",
  "10.22": "Among the Vedas (ancient teachings) I am the Sama Veda. Among the senses I am the mind, and among living beings I am consciousness.",
  "10.23": "Among powerful forces I appear as those that shape creation, and among mountains as the great peaks that rise above the earth.",
  "10.24": "Among guiding intelligences I am wisdom itself, and among vast waters I am the ocean.",
  "10.25": "Among sacred sounds I am the primal syllable. Among immovable forms I am the great mountains.",
  "10.26": "Among trees I am the sacred fig tree, among sages Narada, and among enlightened beings those who embody deep understanding.",
  "10.27": "Among horses I am the noblest, among elephants the most majestic, and among people those who lead with wisdom.",
  "10.28": "Among weapons I am the thunderbolt, among cattle the wish-fulfilling cow, and among forces of creation the impulse that brings life into being.",
  "10.29": "Among serpents I am the cosmic serpent, among waters the lord of the oceans, and among ancestors the guiding spirit of lineage.",
  "10.30": "Among powerful beings I am the righteous among them, among measures I am time, among animals the lion, and among birds the great eagle.",
  "10.31": "Among purifying forces I am the wind, among warriors the noble hero, among creatures of the water the shark, and among rivers the sacred Ganga.",
  "10.32": "In every process of creation I am the beginning, the middle, and the end. Among sciences I am the knowledge of the soul, and among debates fair reasoning.",
  "10.33": "Among letters I am the first sound, among forms of speech the balanced pair, and I am time itself which never ends.",
  "10.34": "I am the force that ends all things and the origin of what is yet to come. Among noble qualities I am wisdom, memory, courage, and forgiveness.",
  "10.35": "Among sacred hymns I am the most uplifting, among poetic rhythms the Gayatri, among months the most fertile, and among seasons the renewal of spring.",
  "10.36": "Among games of chance I am the play itself. I am brilliance in what shines, determination that leads to victory, and goodness within what is good.",
  "10.37": "Among the Vrishnis I am Vasudeva, among the Pandavas I am Arjuna, among sages Vyasa, and among poets Ushanas.",
  "10.38": "Among forces of discipline I am the power that restrains wrongdoing, among strategies wise judgment, among secrets silence, and among the wise knowledge.",
  "10.39": "Whatever seed of existence appears in any being comes from this source. Nothing can exist apart from it.",
  "10.40": "The expressions of this deeper presence are endless. What I have described is only a small glimpse.",
  "10.41": "Whenever you see something magnificent, powerful, or beautiful, recognize it as a reflection of this greater presence.",
  "10.42": "Yet all these examples are only fragments. With a single portion of its being, the source of existence sustains the entire universe."
};

const GITA_DATA_PATH = path.join(__dirname, 'gitaData.ts');

async function main() {
    try {
        const fileContent = fs.readFileSync(GITA_DATA_PATH, 'utf-8');
        
        const arrayStartMarker = "export const GITA_VERSES: GitaVerse[] = ";
        const arrayStartIndex = fileContent.indexOf(arrayStartMarker);
        if (arrayStartIndex === -1) {
            console.error("Could find GITA_VERSES array start.");
            return;
        }
        
        const arrayBodyStart = arrayStartIndex + arrayStartMarker.length;
        
        const arrayEndIdx = fileContent.indexOf("export const getVersesByChapter", arrayBodyStart);
        if (arrayEndIdx === -1) {
             console.error("Could not find GITA_VERSES array end.");
             return;
        }
        
        let bracketIndex = arrayEndIdx;
        while (bracketIndex > arrayBodyStart && fileContent[bracketIndex] !== ']') {
            bracketIndex--;
        }

        const arrayString = fileContent.substring(arrayBodyStart, bracketIndex + 1);
        const restOfFile = fileContent.substring(bracketIndex + 1);

        let verses;
        try {
            verses = eval(arrayString);
        } catch (e) {
            console.error("Failed to eval GITA_VERSES:", e);
            return;
        }

        let updatedCount = 0;
        verses.forEach(localVerse => {
            const verseId = `${localVerse.chapter}.${localVerse.verse}`;
            if (modernVerses[verseId]) {
                localVerse.modernText = modernVerses[verseId];
                updatedCount++;
            }
        });

        console.log(`Updated ${updatedCount} verses with modernText.`);

        const newVersesArrayString = JSON.stringify(verses, null, 4);
        const newContent = fileContent.substring(0, arrayBodyStart) + newVersesArrayString + restOfFile;
        fs.writeFileSync(GITA_DATA_PATH, newContent);
        console.log("Successfully updated gitaData.ts with modernText.");
    } catch (error) {
        console.error("Uncaught error:", error);
    }
}

main();
