import fs from 'fs';
import path from 'path';

const filePath = path.join(process.cwd(), 'gitaData.ts');
let content = fs.readFileSync(filePath, 'utf8');

const themeData = [
  // Chapter 2
  { id: "2-14", themes: ["equanimity", "clarity"] },
  { id: "2-15", themes: ["equanimity", "courage"] },
  { id: "2-16", themes: ["knowledge", "clarity"] },
  { id: "2-17", themes: ["knowledge"] },
  { id: "2-22", themes: ["clarity", "knowledge"] },
  { id: "2-23", themes: ["clarity"] },
  { id: "2-24", themes: ["knowledge"] },
  { id: "2-25", themes: ["clarity"] },
  { id: "2-27", themes: ["clarity", "equanimity"] },
  { id: "2-38", themes: ["equanimity", "action"] },
  { id: "2-40", themes: ["courage", "clarity"] },
  { id: "2-41", themes: ["clarity"] },
  { id: "2-45", themes: ["detachment", "clarity"] },
  { id: "2-46", themes: ["knowledge", "clarity"] },
  { id: "2-47", themes: ["action", "detachment"] },
  { id: "2-48", themes: ["equanimity", "action"] },
  { id: "2-49", themes: ["detachment", "action"] },
  { id: "2-50", themes: ["action", "clarity"] },
  { id: "2-51", themes: ["detachment", "knowledge"] },
  { id: "2-58", themes: ["meditation", "detachment"] },
  { id: "2-59", themes: ["clarity", "detachment"] },
  { id: "2-60", themes: ["clarity"] },
  { id: "2-61", themes: ["meditation", "clarity"] },
  { id: "2-62", themes: ["clarity"] },
  { id: "2-63", themes: ["clarity"] },
  { id: "2-64", themes: ["equanimity", "detachment"] },
  { id: "2-65", themes: ["clarity", "equanimity"] },
  { id: "2-66", themes: ["clarity"] },
  { id: "2-67", themes: ["clarity"] },
  { id: "2-68", themes: ["meditation"] },
  { id: "2-69", themes: ["knowledge", "clarity"] },
  { id: "2-70", themes: ["equanimity", "detachment"] },
  { id: "2-71", themes: ["detachment", "equanimity"] },
  { id: "2-72", themes: ["knowledge", "clarity"] },
  // Chapter 3
  { id: "3-4", themes: ["action", "clarity"] },
  { id: "3-5", themes: ["action"] },
  { id: "3-7", themes: ["action"] },
  { id: "3-8", themes: ["duty", "action"] },
  { id: "3-9", themes: ["action", "detachment"] },
  { id: "3-16", themes: ["duty", "clarity"] },
  { id: "3-19", themes: ["action", "detachment"] },
  { id: "3-21", themes: ["duty", "action"] },
  { id: "3-25", themes: ["action", "detachment"] },
  { id: "3-27", themes: ["clarity", "knowledge"] },
  { id: "3-28", themes: ["knowledge", "clarity"] },
  { id: "3-30", themes: ["surrender", "action", "detachment"] },
  { id: "3-31", themes: ["devotion", "action"] },
  { id: "3-33", themes: ["clarity"] },
  { id: "3-34", themes: ["detachment", "clarity"] },
  { id: "3-35", themes: ["duty", "courage"] },
  { id: "3-37", themes: ["clarity"] },
  { id: "3-38", themes: ["clarity"] },
  { id: "3-39", themes: ["clarity"] },
  { id: "3-40", themes: ["clarity"] },
  { id: "3-41", themes: ["action"] },
  { id: "3-42", themes: ["knowledge", "clarity"] },
  { id: "3-43", themes: ["courage", "clarity"] },
  // Chapter 4
  { id: "4-9", themes: ["knowledge", "devotion"] },
  { id: "4-10", themes: ["detachment", "knowledge"] },
  { id: "4-11", themes: ["devotion"] },
  { id: "4-14", themes: ["detachment", "action"] },
  { id: "4-16", themes: ["clarity"] },
  { id: "4-17", themes: ["clarity"] },
  { id: "4-18", themes: ["knowledge", "action"] },
  { id: "4-19", themes: ["knowledge"] },
  { id: "4-20", themes: ["detachment", "action"] },
  { id: "4-21", themes: ["detachment", "action"] },
  { id: "4-22", themes: ["equanimity", "detachment"] },
  { id: "4-23", themes: ["action", "detachment"] },
  { id: "4-24", themes: ["knowledge"] },
  { id: "4-31", themes: ["action", "devotion"] },
  { id: "4-33", themes: ["knowledge"] },
  { id: "4-34", themes: ["knowledge", "clarity"] },
  { id: "4-35", themes: ["knowledge"] },
  { id: "4-36", themes: ["courage", "knowledge"] },
  { id: "4-37", themes: ["knowledge"] },
  { id: "4-38", themes: ["knowledge"] },
  { id: "4-39", themes: ["knowledge", "devotion"] },
  { id: "4-40", themes: ["clarity"] },
  { id: "4-41", themes: ["detachment", "knowledge"] },
  { id: "4-42", themes: ["courage", "action"] },
  // Chapter 5
  { id: "5-3", themes: ["detachment", "clarity"] },
  { id: "5-5", themes: ["knowledge", "action"] },
  { id: "5-6", themes: ["action", "clarity"] },
  { id: "5-7", themes: ["knowledge", "equanimity"] },
  { id: "5-8", themes: ["clarity"] },
  { id: "5-9", themes: ["clarity"] },
  { id: "5-10", themes: ["surrender", "detachment", "action"] },
  { id: "5-11", themes: ["action"] },
  { id: "5-12", themes: ["detachment", "equanimity"] },
  { id: "5-18", themes: ["equanimity", "knowledge"] },
  { id: "5-19", themes: ["equanimity", "knowledge"] },
  { id: "5-20", themes: ["equanimity"] },
  { id: "5-21", themes: ["meditation", "clarity"] },
  { id: "5-22", themes: ["clarity", "detachment"] },
  { id: "5-23", themes: ["courage"] },
  { id: "5-24", themes: ["meditation", "knowledge"] },
  { id: "5-25", themes: ["knowledge"] },
  { id: "5-26", themes: ["detachment", "meditation"] },
  { id: "5-27", themes: ["meditation"] },
  { id: "5-28", themes: ["meditation"] },
  { id: "5-29", themes: ["devotion", "clarity"] },
  // Chapter 6
  { id: "6-1", themes: ["action", "detachment"] },
  { id: "6-2", themes: ["detachment", "clarity"] },
  { id: "6-3", themes: ["action", "meditation"] },
  { id: "6-4", themes: ["detachment", "meditation"] },
  { id: "6-5", themes: ["clarity", "courage"] },
  { id: "6-6", themes: ["clarity"] },
  { id: "6-7", themes: ["equanimity", "meditation"] },
  { id: "6-8", themes: ["equanimity", "knowledge"] },
  { id: "6-9", themes: ["equanimity"] },
  { id: "6-10", themes: ["meditation"] },
  { id: "6-11", themes: ["meditation"] },
  { id: "6-12", themes: ["meditation"] },
  { id: "6-13", themes: ["meditation"] },
  { id: "6-14", themes: ["meditation", "devotion"] },
  { id: "6-15", themes: ["meditation"] },
  { id: "6-16", themes: ["clarity"] },
  { id: "6-17", themes: ["clarity", "equanimity"] },
  { id: "6-18", themes: ["meditation"] },
  { id: "6-19", themes: ["meditation"] },
  { id: "6-20", themes: ["meditation", "knowledge"] },
  { id: "6-21", themes: ["knowledge"] },
  { id: "6-22", themes: ["equanimity"] },
  { id: "6-23", themes: ["detachment", "courage"] },
  { id: "6-24", themes: ["detachment", "meditation"] },
  { id: "6-25", themes: ["meditation"] },
  { id: "6-26", themes: ["meditation"] },
  { id: "6-27", themes: ["meditation", "equanimity"] },
  { id: "6-28", themes: ["meditation"] },
  { id: "6-29", themes: ["knowledge", "equanimity"] },
  { id: "6-30", themes: ["devotion", "knowledge"] },
  { id: "6-31", themes: ["devotion"] },
  { id: "6-32", themes: ["equanimity"] },
  { id: "6-35", themes: ["meditation", "detachment"] },
  { id: "6-36", themes: ["meditation"] },
  { id: "6-40", themes: ["courage"] },
  { id: "6-43", themes: ["knowledge"] },
  { id: "6-44", themes: ["knowledge"] },
  { id: "6-45", themes: ["meditation", "knowledge"] },
  { id: "6-46", themes: ["knowledge"] },
  { id: "6-47", themes: ["devotion"] },
  // Chapter 7
  { id: "7-1", themes: ["devotion", "knowledge"] },
  { id: "7-2", themes: ["knowledge"] },
  { id: "7-3", themes: ["knowledge"] },
  { id: "7-4", themes: ["knowledge"] },
  { id: "7-5", themes: ["knowledge"] },
  { id: "7-6", themes: ["knowledge"] },
  { id: "7-7", themes: ["knowledge"] },
  { id: "7-8", themes: ["knowledge"] },
  { id: "7-9", themes: ["knowledge"] },
  { id: "7-10", themes: ["knowledge"] },
  { id: "7-11", themes: ["clarity"] },
  { id: "7-12", themes: ["knowledge"] },
  { id: "7-13", themes: ["clarity"] },
  { id: "7-14", themes: ["surrender", "devotion"] },
  { id: "7-16", themes: ["devotion"] },
  { id: "7-17", themes: ["devotion", "knowledge"] },
  { id: "7-18", themes: ["devotion"] },
  { id: "7-19", themes: ["knowledge", "devotion"] },
  { id: "7-20", themes: ["clarity"] },
  { id: "7-21", themes: ["devotion"] },
  { id: "7-22", themes: ["devotion"] },
  { id: "7-23", themes: ["clarity"] },
  { id: "7-24", themes: ["clarity"] },
  { id: "7-25", themes: ["clarity"] },
  { id: "7-26", themes: ["knowledge"] },
  { id: "7-27", themes: ["clarity"] },
  { id: "7-28", themes: ["devotion"] },
  { id: "7-29", themes: ["knowledge"] },
  { id: "7-30", themes: ["knowledge", "devotion"] },
  // Chapter 8
  { id: "8-5", themes: ["devotion"] },
  { id: "8-6", themes: ["clarity"] },
  { id: "8-7", themes: ["action", "devotion"] },
  { id: "8-8", themes: ["meditation", "devotion"] },
  { id: "8-9", themes: ["meditation"] },
  { id: "8-10", themes: ["meditation"] },
  { id: "8-11", themes: ["knowledge"] },
  { id: "8-12", themes: ["meditation"] },
  { id: "8-13", themes: ["meditation", "devotion"] },
  { id: "8-14", themes: ["devotion"] },
  { id: "8-15", themes: ["knowledge"] },
  { id: "8-16", themes: ["clarity"] },
  { id: "8-17", themes: ["knowledge"] },
  { id: "8-18", themes: ["knowledge"] },
  { id: "8-19", themes: ["clarity"] },
  { id: "8-20", themes: ["knowledge"] },
  { id: "8-21", themes: ["knowledge"] },
  { id: "8-22", themes: ["devotion"] },
  { id: "8-23", themes: ["knowledge"] },
  { id: "8-26", themes: ["clarity"] },
  { id: "8-27", themes: ["clarity"] },
  { id: "8-28", themes: ["knowledge"] },
  // Chapter 9
  { id: "9-1", themes: ["knowledge"] },
  { id: "9-2", themes: ["knowledge"] },
  { id: "9-3", themes: ["clarity"] },
  { id: "9-4", themes: ["knowledge"] },
  { id: "9-5", themes: ["knowledge"] },
  { id: "9-6", themes: ["clarity"] },
  { id: "9-7", themes: ["knowledge"] },
  { id: "9-8", themes: ["knowledge"] },
  { id: "9-9", themes: ["detachment"] },
  { id: "9-10", themes: ["knowledge"] },
  { id: "9-11", themes: ["clarity"] },
  { id: "9-12", themes: ["clarity"] },
  { id: "9-13", themes: ["devotion"] },
  { id: "9-14", themes: ["devotion"] },
  { id: "9-15", themes: ["knowledge", "devotion"] },
  { id: "9-16", themes: ["knowledge"] },
  { id: "9-17", themes: ["knowledge"] },
  { id: "9-18", themes: ["knowledge"] },
  { id: "9-19", themes: ["knowledge"] },
  { id: "9-20", themes: ["clarity"] },
  { id: "9-21", themes: ["clarity"] },
  { id: "9-22", themes: ["devotion", "surrender"] },
  { id: "9-23", themes: ["devotion"] },
  { id: "9-24", themes: ["knowledge"] },
  { id: "9-25", themes: ["clarity"] },
  { id: "9-26", themes: ["devotion"] },
  { id: "9-27", themes: ["action", "devotion"] },
  { id: "9-28", themes: ["detachment", "surrender"] },
  { id: "9-29", themes: ["equanimity"] },
  { id: "9-30", themes: ["devotion", "courage"] },
  { id: "9-31", themes: ["devotion", "courage"] },
  { id: "9-32", themes: ["devotion"] },
  { id: "9-33", themes: ["devotion"] },
  { id: "9-34", themes: ["devotion", "surrender"] },
  // Chapter 10
  { id: "10-3", themes: ["knowledge"] },
  { id: "10-7", themes: ["knowledge"] },
  { id: "10-8", themes: ["devotion", "knowledge"] },
  { id: "10-9", themes: ["devotion"] },
  { id: "10-10", themes: ["knowledge", "devotion"] },
  { id: "10-11", themes: ["knowledge"] },
  { id: "10-20", themes: ["knowledge"] },
  { id: "10-32", themes: ["knowledge"] },
  { id: "10-41", themes: ["clarity"] },
  { id: "10-42", themes: ["knowledge"] }
];

themeData.forEach(item => {
  // More robust regex: find an object that has the specific id and a themes array within the SAME curly braces
  const regex = new RegExp('(\\{[^{}]*"id":\\s*"' + item.id + '"[^{}]*"themes":\\s*)\\[.*?\\]', 'g');
  const replacement = `$1${JSON.stringify(item.themes)}`;
  
  if (content.match(regex)) {
    content = content.replace(regex, replacement);
  } else {
    console.warn(`Could not find verse ${item.id} with themes array.`);
  }
});

fs.writeFileSync(filePath, content, 'utf8');
console.log(`Successfully updated ${themeData.length} verses with themes.`);
